# Generated by Django 3.2.6 on 2021-08-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_project_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
