# Generated by Django 3.2.6 on 2021-08-05 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Item',
        ),
    ]
