# Generated by Django 3.2.6 on 2021-08-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_tags_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
